### ISSUE TITLE
"Symbolic" references do not work for static fields

### ISSUE THREAD

**Issue by tdegueul** [crossminer/maracas#45]
APIv1:
```
class A { public static int f; }
class B extends A {}
```

APIv2:
```
class A { public int f; }
class B extends A {}
```

Client:
```
class C {
    public int access1() { return A.f; }
    public int access2() { return B.f; }
```

Maracas correctly reports a breaking change in `access1()`, but not in `access2()`.

**Comment by lmove** [comment]
This issue affects `annotationDeprecatedAdded`, `fieldNowStatic`, `fieldNowFinal`, `fieldRemoved`, and `fieldTypeChanged` detections. More tests are needed.
